### ISSUE TITLE
在windows下打开浏览器失败

### ISSUE THREAD

**Issue by Tzxhy** [hiproxy/hiproxy#47]
node版本：8.9.3
启动命令：hiproxy start -o chrome
报错：
```bash
(node:10628) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Can not find browser info
(node:10628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
猜测是打开浏览器的npm包不兼容windows，望回复。

**Comment by zdying** [comment]
提供一下windows中安装的chrome版本号

**Comment by Tzxhy** [comment]
初步判断是 op-browser 不兼容. 在包op-browser/test里测试open，得：
```bash
chrome detect fail: Error: Can not find browser info
    at E:\npm_module\node_modules\hiproxy\node_modules\op-browser\lib\index.js:143:16
    at new Promise (<anonymous>)
    at Object.detect (E:\npm_module\node_modules\hiproxy\node_modules\op-browser\lib\index.js:103:12)
    at E:\npm_module\node_modules\hiproxy\node_modules\op-browser\test\open.js:4:6
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\npm_module\node_modules\hiproxy\node_modules\op-browser\test\open.js:3:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

chrome版本：65.0.3325.146（正式版本） （32 位）

**Comment by zdying** [comment]
windows什么版本？

**Comment by Tzxhy** [comment]
![image](https://user-images.githubusercontent.com/18610809/38468996-855176ee-3b80-11e8-90ee-64355304fd47.png)

**Comment by Tzxhy** [comment]
HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Path 注册表下就没有chrome.exe，估计不同windows版本注册表结构可能有啥不一样。

**Comment by zdying** [comment]
确实，Windows 10，没有测试过，等有空了看看。如果你有时间，可以帮忙修复一下 :)
