### ISSUE TITLE
hiproxy挂了

### ISSUE THREAD

**Issue by yadongxie150** [hiproxy/hiproxy#61]
最近在开发过程中，经常遇到hiproxy挂了的情况，麻烦给看看是什么情况，截图如下：
`
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by zdying** [comment]
麻烦提供一下Node.js版本号，以及hiproxy的版本；

也可以试试最新的测试版本，看是否还有这个问题。最新测试版安装方法：

```bash
npm install hiproxy@next
```

**Comment by yadongxie150** [comment]
- node 版本： v10.15.3
- hiproxy版本：v1.3.1

原先以为是自己电脑的问题（别人电脑上是好的），今天换了新电脑，node、hiproxy都是从头装的，还是有这个问题，启动后很快就会挂掉。

**Comment by yadongxie150** [comment]
下载最新的测试版本以后没问题了，是正式版有问题

**Comment by zdying** [comment]
感谢反馈！
