### ISSUE TITLE
`Log` not defined

### ISSUE THREAD

**Issue by poland-can-into-space** [hiproxy/hiproxy#62]
Did I miss something?
I got this error, `log` was not defined. 
```
C:\Users\MyPC\front\rp\node_modules\hiproxy\src\rewrite\index.js:254
    log.detail(JSON.stringify(this._rules));
        ^

TypeError: log.detail is not a function
    at Rewrite.update (C:\Users\MyPC\front\rp\node_modules\hiproxy\src\rewrite\index.js:254:9)
    at Rewrite.addFile (C:\Users\MyPC\front\rp\node_modules\hiproxy\src\rewrite\index.js:44:12)
    at ProxyServer.addRewriteFile (C:\Users\MyPC\front\rp\node_modules\hiproxy\src\server.js:164:18)
    at Object.<anonymous> (C:\Users\MyPC\front\rp\server.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Comment by zdying** [comment]
hi @poland-can-into-space , Could you send me the code that throws this error ?

**Comment by poland-can-into-space** [comment]
Hi @zdying 
hiproxy version is latest and code is here (80th line): 
https://github.com/hiproxy/hiproxy/blob/master/src/rewrite/getProxyInfo.js

**Comment by zdying** [comment]
Do you use hiproxy as a dependence? Could you provide a example project that can reproduce this problem?
