### ISSUE TITLE
Error: write EPIPE     at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)

### ISSUE THREAD

**Issue by Huang-Jacky** [hiproxy/hiproxy#64]
[access] CONNECT ilce.alicdn.com:443
[access] CONNECT ilce.alicdn.com:443
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:713:12)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)

hiproxy version:1.3.1
node version:10.15.3

**Comment by SimeriaIonut** [comment]
Did you find the solution to this issue? I have the same problem

**Comment by xwartz** [comment]
+1
