### ISSUE TITLE
hiproxy start -o  error

### ISSUE THREAD

**Issue by Huo613** [hiproxy/hiproxy#66]
The detail message is:
TypeError: Cannot read property 'domains' of null
    at Transform.mergeProps (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/node_modules/hiproxy-conf-parser/src/transform.js:148:25)
    at Transform.transform (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/node_modules/hiproxy-conf-parser/src/transform.js:13:10)
    at Function.Rewrite.parse (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/src/rewrite/index.js:265:48)
    at Function.Rewrite.parseFile (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/src/rewrite/index.js:317:18)
    at Rewrite.update (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/src/rewrite/index.js:238:45)
    at Rewrite.addFile (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/src/rewrite/index.js:44:12)
    at ProxyServer.addRewriteFile (/Users/sherohuo/.nvm/versions/node/v6.2.0/lib/node_modules/hiproxy/src/server.js:164:18)

**Comment by huaziHear** [comment]
麻烦把rewrite文件或者hosts文件一起贴出来
